config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moneymanager.urls')),
    path('users/', include('users.urls')),


]

users/urls.py
from django.urls import path
from .views import SignUp, login_page,  logout_page, profile_page

app_name="users"
urlpatterns = [
    path("register/", SignUp.as_view(), name="register"),
    path("login/", login_page, name="login"),
    path("logout/", logout_page, name="logout"),
    path("profile/", profile_page, name="profile"),  
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User

class UserUpdateForm(forms.ModelForm):
    new_password = forms.CharField(
        widget=forms.PasswordInput,
        required=False,
        label='New Password'
    )

    class Meta:
        model = User
        fields = ['username']  # List of fields to include in the form

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")

        if new_password:
            if len(new_password) < 8:
                self.add_error('new_password', 'Password must be at least 8 characters long.')
        return cleaned_data

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .forms import UserUpdateForm
from django.contrib.auth import update_session_auth_hash

def login_required_decorator(func):
    return login_required(func, login_url='users:login')


@login_required_decorator
def logout_page(request):
    logout(request)
    return redirect('users:login')
# Create your views here.


def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('moneymanager:home')
    return render(request, 'login.html')

@login_required_decorator
def home_page(request):
    return render(request, 'index.html')

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'registration.html'


@login_required
def profile_page(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            new_password = form.cleaned_data.get('new_password')
            if new_password:
                user.set_password(new_password)
            user.save()
            return redirect('users:login')
    else:
        form = UserUpdateForm(instance=request.user)

    return render(request, 'profile.html', {'form': form})

users/templates/login.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <title>Kirish sahifasi</title>
    <style>
    * {
        box-sizing: border-box;
    }

    body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .container {
        width: 100%;
        max-width: 400px;
        margin: 20px;
        padding: 30px;
        background-color: #ffffff;
        box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
        text-align: center;
    }

    h2 {
        color: #333;
        margin-bottom: 20px;
    }

    .form-group {
        margin-bottom: 15px;
        text-align: left;
    }

    label {
        display: block;
        font-size: 14px;
        color: #555;
        margin-bottom: 5px;
    }

    input {
        width: calc(100% - 20px);
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    button {
        width: 100%;
        padding: 12px;
        background-color: #6a1b9a;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease;
        margin-top: 10px;
    }

    button:hover {
        background-color: #4a148c;
    }

    .link {
        margin-top: 20px;
    }

    .link button {
        width: 100%;
        padding: 12px;
        background-color: #6a1b9a;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .link button:hover {
        background-color: #4a148c;
    }
    </style>
</head>
<body>
    <div class="container">
        <h2>Kirish</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Foydalanuvchi nomi yoki Email:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Parol:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Kirish</button>
        </form>
        <div class="link">
            <form action="{% url 'users:register' %}" method="get">
                <button type="submit">Ro'yxatdan o'tish</button>
            </form>

        </div>

    </div>
</body>
</html>

users/templates/profile.html
{% extends 'base.html' %}

{% block title %}
    Profile - Mini Finance
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Profile</h1>
</div>

<div class="row">
    <div class="col-md-8">
        <form method="POST" class="form-horizontal">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.username.label_tag }}
                {{ form.username }}
                {% if form.username.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.username.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                {{ form.new_password.label_tag }}
                {{ form.new_password }}
                {% if form.new_password.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.new_password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <button type="submit" class="btn btn-primary">Update Profile</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/registration.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <title>Ro'yxatga olish sahifasi</title>
    <style>
    * {
        box-sizing: border-box;
    }

    body {
        font-family: Arial, sans-serif;
        background-color: #f0f0f0;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .container {
        width: 100%;
        max-width: 400px;
        margin: 20px;
        padding: 30px;
        background-color: #ffffff;
        box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
        text-align: center;
    }

    h2 {
        color: #333;
        margin-bottom: 20px;
    }

    .form-group {
        margin-bottom: 15px;
        text-align: left;
    }

    label {
        display: block;
        font-size: 14px;
        color: #555;
        margin-bottom: 5px;
    }

    input {
        width: calc(100% - 20px);
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }

    button {
        width: 100%;
        padding: 12px;
        background-color: #a239bf;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s ease;
        margin-top: 10px;
    }

    button:hover {
        background-color: #d42fda;
    }

    .form-group .error {
        color: red;
        font-size: 12px;
    }

    .form-group small {
        color: grey;
    }

    .au-input--full {
        display: flex;
        align-items: center;
    }

    .login-link {
        margin-top: 15px;
        font-size: 14px;
    }

    .login-link a {
        color: #a239bf;
        text-decoration: none;
    }

    .login-link a:hover {
        text-decoration: underline;
    }
    </style>
</head>
<body>
    <div class="container">
        <h2>Ro'yxatga olish</h2>
        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    <div class="au-input au-input--full">{{ field }}</div>
                    {% if field.help_text %}
                        <small>{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit">Ro'yxatdan o'tish</button>
        </form>
        <div class="login-link">
            <p>Allaqachon hisobingiz bormi? <a href="{% url 'users:login' %}">Tizimga kirish</a></p>
        </div>
    </div>
</body>
</html>